data:
  datasets:
    train:
      - libribrain_phoneme:
          data_path: "./data"
          preprocessing_str: "bads+headpos+sss+notch+bp+ds"
          label_type: "phoneme"
          standardize: true
          tmin: 0.0
          tmax: 0.5
          partition: "train"
          preload_files: true
    val:
      - libribrain_phoneme:
          data_path: "./data"
          standardize: true
          tmin: 0.0
          tmax: 0.5
          partition: "validation"
          preload_files: true
    test:
      - libribrain_phoneme:
          data_path: "./data"
          standardize: true
          tmin: 0.0
          tmax: 0.5
          partition: "test"
          preload_files: false
  dataloader:
    batch_size: 256
    num_workers: 8
  general:
    inMemory: False
    averaged_samples: 100
    repeat: 5
    shuffle: True
    balance: True
    augment: False

model:
  name: baseline
  params:
    embedding_dim: 256
    lr: 0.0001

trainer:
  max_epochs: 10

general:
  wandb: True
  output_path: "./out/phoneme-baseline-xl"
  checkpoint_path: "./out/phoneme-baseline-xl"
  seed: 42
  use_tf32: True
