data:
  datasets:
    train:
      - libribrain_phoneme:
          data_path: "./data"
          preprocessing_str: "bads+headpos+sss+notch+bp+ds"
          label_type: "phoneme"
          standardize: true
          tmin: 0.0
          tmax: 0.5
          partition: "train"
          preload_files: true

    val:
      - libribrain_phoneme:
          data_path: "./data"
          standardize: true
          tmin: 0.0
          tmax: 0.5
          partition: "validation"
          preload_files: true
    test:
      - libribrain_phoneme:
          data_path: "./data"
          standardize: true
          tmin: 0.0
          tmax: 0.5
          partition: "test"
          preload_files: false
  dataloader:
    batch_size: 256
    num_workers: 8
  general:
    inMemory: False
    averaged_samples: 100
    repeat: 5
    shuffle: True
    balance: True
    augment: False

model:
  # data.shape = (, 306, num_samples=125)
  - conv1d:
      in_channels: 306
      out_channels: 256
      kernel_size: 7
      stride: 1
      padding: "same"
  # data.shape = (, 256, 125)
  - resnet_block:
      model_config:
        - elu:
        - conv1d:
            in_channels: 256
            out_channels: 256
            kernel_size: 3
            stride: 1
            padding: "same"
        - elu:
        - conv1d:
            in_channels: 256
            out_channels: 256
            kernel_size: 1
            stride: 1
            padding: "same"
  # data.shape = (, 256, 125)
  - elu:
  - conv1d:
      in_channels: 256
      out_channels: 256
      kernel_size: 3
      stride: 1
      padding: "same"
  # data.shape = (, 256, 125)
  - resnet_block:
      model_config:
        - elu:
        - conv1d:
            in_channels: 256
            out_channels: 256
            kernel_size: 3
            stride: 1
            padding: "same"
        - elu:
        - conv1d:
            in_channels: 256
            out_channels: 256
            kernel_size: 1
            stride: 1
            padding: "same"
  - elu:
  # data.shape = (, 256, 125)
  - conv1d:
      in_channels: 256
      out_channels: 256
      kernel_size: 50
      stride: 25
  - elu:
  # data.shape = (, 256, 4)
  - conv1d:
      in_channels: 256
      out_channels: 256
      kernel_size: 7
      stride: 1
      padding: "same"
  - elu:
  # data.shape = (, 256, 4)
  - conv1d:
      in_channels: 256
      out_channels: 1024
      kernel_size: 4
      padding: 0
  - relu:
  # - dropout:
  #     p: 0.5
  - flatten:
  # data.shape = (, 1024)
  - lstm:
      input_size: 1024
      hidden_size: 512
      num_layers: 2
      bias: true
      batch_first: true
      dropout: 0.5
      bidirectional: false
  - linear:
      in_features: 512
      out_features: 39

loss:
  name: cross_entropy
  
optimizer:
  name: adam
  config:
    lr: 0.0001

trainer:
  max_epochs: 30

general:
  wandb: True
  output_path: "./out/phoneme-baseline-xl"
  checkpoint_path: "./out/phoneme-baseline-xl"
  seed: 42
  use_tf32: True
