data:
  datasets:
    train:
      - libribrain_phoneme:
          data_path: "./data"
          preprocessing_str: "bads+headpos+sss+notch+bp+ds"
          label_type: "phoneme"
          standardize: true
          tmin: 0.0
          tmax: 0.5
          partition: "train"
          preload_files: false
    val:
      - libribrain_phoneme:
          data_path: "./data"
          standardize: true
          tmin: 0.0
          tmax: 0.5
          partition: "validation"
          preload_files: false
    test:
      - libribrain_phoneme:
          data_path: "./data"
          standardize: true
          tmin: 0.0
          tmax: 0.5
          partition: "test"
          preload_files: false
  dataloader:
    batch_size: 256
    num_workers: 4
  general:
    inMemory: False
    averaged_samples: 100
    repeat: 1
    shuffle: True
    balance: True
    augment: False

model:
  name: megt
  params:
    d_model: 256
    nhead: 8
    transformer_activation: gelu
    transformer_num_layers: 4
    lr: 0.0001

trainer:
  max_epochs: 10

general:
  wandb: true
  output_path: "./out/phoneme-megt2"
  checkpoint_path: "./out/phoneme-megt2"
  seed: 42
  use_tf32: True
