data:
  datasets:
    train:
      - libribrain_phoneme:
          data_path: "./data"
          preprocessing_str: "bads+headpos+sss+notch+bp+ds"
          label_type: "phoneme"
          standardize: true
          tmin: 0.0
          tmax: 0.5
          partition: "train"
          preload_files: false

    val:
      - libribrain_phoneme:
          data_path: "./data"
          standardize: true
          tmin: 0.0
          tmax: 0.5
          partition: "validation"
          preload_files: false
    test:
      - libribrain_phoneme:
          data_path: "./data"
          standardize: true
          tmin: 0.0
          tmax: 0.5
          include_run_keys: [["0", "12", "Sherlock1", "2"]]
          preload_files: false
  dataloader:
    batch_size: 256
    num_workers: 16
  general:
    inMemory: False
    averaged_samples: 100

model:
  # data.shape = (, 306, num_samples=125)
  - conv1d:
      in_channels: 306
      out_channels: 256
      kernel_size: 7
      stride: 1
      padding: "same"
  # data.shape = (, 256, 125)
  - resnet_block:
      model_config:
        - elu:
        - conv1d:
            in_channels: 256
            out_channels: 256
            kernel_size: 3
            stride: 1
            padding: "same"
        - elu:
        - conv1d:
            in_channels: 256
            out_channels: 256
            kernel_size: 1
            stride: 1
            padding: "same"
  # data.shape = (, 256, 125)
  - elu:
  - conv1d:
      in_channels: 256
      out_channels: 256
      kernel_size: 3
      stride: 1
      padding: "same"
  # data.shape = (, 256, 125)
  - resnet_block:
      model_config:
        - elu:
        - conv1d:
            in_channels: 256
            out_channels: 256
            kernel_size: 3
            stride: 1
            padding: "same"
        - elu:
        - conv1d:
            in_channels: 256
            out_channels: 256
            kernel_size: 1
            stride: 1
            padding: "same"
  - elu:
  # data.shape = (, 256, 125)
  - conv1d:
      in_channels: 256
      out_channels: 256
      kernel_size: 50
      stride: 25
  - elu:
  # data.shape = (, 256, 5)
  - conv1d:
      in_channels: 256
      out_channels: 256
      kernel_size: 7
      stride: 1
      padding: "same"
  - elu:
  # data.shape = (, 256, 5)
  - conv1d:
      in_channels: 256
      out_channels: 1024
      kernel_size: 4
      padding: 0
  - relu:
  - dropout:
      p: 0.5
  - conv1d:
      in_channels: 1024
      out_channels: 39
      kernel_size: 1
      padding: 0
  - flatten:

loss:
  name: cross_entropy

optimizer:
  name: adam
  config:
    lr: 0.0001

trainer:
  max_epochs: 30

general:
  wandb: True
  output_path: "./out/phoneme-baseline-l"
  checkpoint_path: "./out/phoneme-baseline-l"
  seed: 42
  use_tf32: True
