data:
  datasets:
    train:
      - libribrain_phoneme:
          data_path: "./data"
          preprocessing_str: "bads+headpos+sss+notch+bp+ds"
          label_type: "phoneme"
          standardize: true
          tmin: 0.0
          tmax: 0.5
          exclude_tasks:
            ["Sherlock3", "Sherlock4", "Sherlock5", "Sherlock6", "Sherlock7"]
          exclude_run_keys:
            [
              ["0", "11", "Sherlock1", "2"],
              ["0", "12", "Sherlock1", "2"],
              ["0", "11", "Sherlock2", "1"],
              ["0", "12", "Sherlock2", "1"],
            ]
          preload_files: false

    val:
      - libribrain_phoneme:
          data_path: "./data"
          standardize: true
          tmin: 0.0
          tmax: 0.5
          partition: "validation"
          preload_files: false
    test:
      - libribrain_phoneme:
          data_path: "./data"
          standardize: true
          tmin: 0.0
          tmax: 0.5
          partition: "test"
          preload_files: false
  dataloader:
    batch_size: 256
    num_workers: 4
  general:
    inMemory: False
    averaged_samples: 0

model:
  - conv1d:
      in_channels: 306
      out_channels: 128
      kernel_size: 7
      stride: 1
      padding: "same"
  - resnet_block:
      model_config:
        - elu:
        - conv1d:
            in_channels: 128
            out_channels: 128
            kernel_size: 3
            stride: 1
            padding: "same"
        - elu:
        - conv1d:
            in_channels: 128
            out_channels: 128
            kernel_size: 1
            stride: 1
            padding: "same"
  - elu:
  - conv1d:
      in_channels: 128
      out_channels: 128
      kernel_size: 50
      stride: 25
  - elu:
  - conv1d:
      in_channels: 128
      out_channels: 128
      kernel_size: 7
      stride: 1
      padding: "same"
  - elu:
  - conv1d:
      in_channels: 128
      out_channels: 512
      kernel_size: 4
      padding: 0
  - relu:
  - dropout:
      p: 0.5
  - conv1d:
      in_channels: 512
      out_channels: 39
      kernel_size: 1
      padding: 0
  - flatten:

loss:
  name: cross_entropy

optimizer:
  name: adam
  config:
    lr: 0.0001

trainer:
  max_epochs: 10

general:
  wandb: True
  output_path: "./out/phoneme-baseline"
  checkpoint_path: "./out/phoneme-baseline"
  seed: 42
  use_tf32: True
